import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("downloadable human and icon symbols use fill-only accent outlines", () => {
  const assetRoot = new URL("../src/assets/", import.meta.url);
  const spritePaths = [
    "humans/apiops-stick-figures-poses.svg",
    "humans/apiops-stick-figures-stories.svg",
    "icons/apiops-iconset.svg",
    "icons/apiops-metro-icons.svg",
  ];
  const accentColors = ["#2f7d32", "#67389b", "#00a6a6", "#1656b8", "#e64c19"];

  for (const spritePath of spritePaths) {
    const sprite = readFileSync(new URL(spritePath, assetRoot), "utf8");
    const downloadableSymbols = [...sprite.matchAll(/<symbol\b[\s\S]*?<\/symbol>/g)].map(([symbol]) => symbol);
    assert.ok(downloadableSymbols.length > 0, `${spritePath} exposes downloadable symbols`);
    assert.doesNotMatch(sprite, /stroke\s*:\s*var\(--apiops-accent|stroke=["']var\(--apiops-accent/i);

    for (const color of accentColors) {
      const escapedColor = color.replace("#", "\\#");
      const accentStroke = new RegExp(`(?:stroke=["']${escapedColor}["']|stroke\\s*:\\s*${escapedColor})(?:[;"'])`, "i");
      assert.doesNotMatch(sprite, accentStroke, `${spritePath} must not stroke with ${color}`);
    }

    const outlinedAccents = downloadableSymbols.flatMap((symbol) =>
      [...symbol.matchAll(/<path\b[^>]*\bfill=["'](#[0-9a-f]{6})["'][^>]*\bstroke=["']none["'][^>]*>/gi)],
    );
    assert.ok(outlinedAccents.length > 0, `${spritePath} has explicit, editor-recolorable accent fills`);
  }
});

test("character grammar notation exposes the implemented backlog symbols", async () => {
  const notation = readFileSync(new URL("../src/assets/icons/apiops-character-notation.svg", import.meta.url), "utf8");
  const scenes = readFileSync(new URL("../src/assets/humans/apiops-character-scenes.svg", import.meta.url), "utf8");
  const sceneConfig = JSON.parse(readFileSync(new URL("../src/assets/character-scenes/scenes.json", import.meta.url), "utf8"));
  const expectedNotationSymbols = [
    "symbol-api",
    "symbol-api-card",
    "symbol-contract",
    "symbol-code-brackets",
    "symbol-curly-contract",
    "symbol-field",
    "symbol-question",
    "symbol-alert",
    "symbol-board",
    "symbol-stop",
    "symbol-blocker",
    "symbol-rocket",
    "symbol-publish",
    "symbol-product-cube",
    "symbol-capability-package",
    "symbol-standard",
    "symbol-standard-placard",
    "symbol-standard-placard-blank",
    "symbol-ownership-api",
    "symbol-megaphone",
    "symbol-workshop-board",
    "symbol-check-bullet",
    "connection-chaos",
    "connection-branching",
    "connection-ownership-claim",
    "connection-missing-conversation",
    "connection-gap",
    "connection-conversion-arrow",
  ];
  const expectedSceneSymbols = [
    "scene-chaos-to-capabilities",
    "scene-shared-picture-missing",
    "scene-local-optimization",
    "scene-consumers-capabilities",
    "scene-governance-vs-innovation",
    "scene-api-first-not-enough",
    "scene-api-lifecycle-loop",
    "scene-api-ownership-question",
    "scene-standards-without-conversation",
    "scene-feedback-invitation",
    "scene-workshop-invitation",
    "scene-team-celebration",
  ];

  for (const id of expectedNotationSymbols) {
    assert.match(notation, new RegExp(`<symbol id="${id}"(?:\\s|>)`), `${id} exists in character notation`);
  }

  for (const id of expectedSceneSymbols) {
    assert.match(scenes, new RegExp(`<symbol id="${id}"(?:\\s|>)`), `${id} exists in character scenes`);
  }

  assert.match(scenes, /Generated by scripts\/build-character-scenes\.mjs/);
  assert.doesNotMatch(scenes, /<image\b/i, "character scenes inline ready-made pose geometry for reliable previews");
  assert.doesNotMatch(scenes, /href="#symbol-/i, "character scenes must not reference unprefixed notation symbols");
  assert.doesNotMatch(scenes, /href="#connection-/i, "character scenes must not reference unprefixed connection symbols");
  assert.match(scenes, /\.no-accent \.accent/);

  for (const id of ["scene-actor-thinking", "scene-actor-announcing", "scene-actor-standing", "scene-actor-dancing"]) {
    assert.match(scenes, new RegExp(`<symbol id="${id}"(?:\\s|>)`), `${id} pose geometry is inlined`);
  }

  for (const id of [
    "scene-symbol-api",
    "scene-symbol-contract",
    "scene-symbol-consumer-group",
    "scene-symbol-product-cube",
    "scene-symbol-architecture-cube",
    "scene-symbol-code-brackets",
    "scene-symbol-code-design",
    "scene-symbol-delivery-gear",
    "scene-symbol-feedback-megaphone",
    "scene-connection-ownership-claim",
    "scene-connection-missing-conversation",
    "scene-connection-conversion-arrow",
  ]) {
    assert.match(scenes, new RegExp(`<symbol id="${id}"(?:\\s|>)`), `${id} notation geometry is inlined`);
  }

  const chaosScene = extractSymbol(scenes, "scene-chaos-to-capabilities");
  assert.equal([...chaosScene.matchAll(/href="#scene-actor-/g)].length, 3);
  assert.equal([...chaosScene.matchAll(/href="#scene-symbol-api"/g)].length, 2);
  assert.equal([...chaosScene.matchAll(/href="#scene-symbol-contract"/g)].length, 1);
  assert.match(chaosScene, /class="dash"/);
  assert.match(chaosScene, /Understand/);
  assert.match(chaosScene, /Enable/);

  const apiSymbol = extractSymbol(scenes, "scene-symbol-api");
  assert.doesNotMatch(apiSymbol, /class="accent"/, "generated scene notation suppresses source accent dots");

  const localOptimizationScene = extractSymbol(scenes, "scene-local-optimization");
  assert.match(localOptimizationScene, /#scene-symbol-api/);
  assert.match(localOptimizationScene, /#scene-symbol-contract/);
  assert.match(localOptimizationScene, /#scene-symbol-field/);

  const consumersScene = extractSymbol(scenes, "scene-consumers-capabilities");
  assert.match(consumersScene, /viewBox="0 0 180 132"/, "consumer scene can crop actors to torso-only");

  const ownershipScene = extractSymbol(scenes, "scene-api-ownership-question");
  assert.match(ownershipScene, /scale\(-1 1\)/, "ownership scene can flip actors toward the central API");

  const lifecycleScene = extractSymbol(scenes, "scene-api-lifecycle-loop");
  for (const id of [
    "scene-symbol-consumer-group",
    "scene-symbol-architecture-cube",
    "scene-symbol-code-design",
    "scene-symbol-delivery-gear",
    "scene-symbol-feedback-megaphone",
  ]) {
    assert.match(lifecycleScene, new RegExp(`href="#${id}"`), `lifecycle scene uses ${id}`);
  }

  const { default: sharp } = await import("sharp");
  const metadata = await sharp(Buffer.from(scenes)).metadata();
  assert.equal(metadata.width, sceneConfig.canvas.width);
  assert.equal(metadata.height, sceneConfig.canvas.height);
});

test("SVG downloads retain embedded sprite definitions", () => {
  const component = readFileSync(new URL("../src/react/index.tsx", import.meta.url), "utf8");
  assert.match(component, /document\.querySelectorAll\("defs"\)/);
  assert.match(component, /<defs>\$\{embeddedDefinitions\}\$\{symbol\.outerHTML\}<\/defs>/);
});

function extractSymbol(svg, id) {
  const match = svg.match(new RegExp(`<symbol id="${id}"(?:\\s|>)[\\s\\S]*?<\\/symbol>`));
  assert.ok(match, `${id} exists`);
  return match[0];
}
