import type { Locale } from "../lib/method-data";

export type FaqItem = { question: string; answer: string };

const english: FaqItem[] = [
  { question: "Why is retiring APIs not a lifecycle stage in APIOps Cycles?", answer: `Retirement is covered across three existing stations rather than treated as a separate stage. API Product Strategy is where teams decide whether to continue, pivot, or retire a product, using the Customer Journey, API Value Proposition, and API Business Model canvases. Monitoring & Improving provides evidence such as declining usage, consumer feedback, cost-to-benefit ratios, and security risks. Release Management then covers version lifecycle policies, deprecation and sunset communication, backward compatibility, redirects, and fallback plans. In short: retirement is a product decision, supported by evidence and carried out through release management.` },
  { question: "How can I integrate APIOps Cycles with our Agile or SAFe process?", answer: `Treat stations as workshops or backlog-refinement steps within your existing cadence. Use canvases in early sprints for discovery, and revisit stations such as API Audit and Metrics & Analytics during inspect-and-adapt cycles. In SAFe, the stations align well with Enabler Epics and portfolio-level governance.` },
  { question: "What is the best way to run an API Audit, and how often should I do it?", answer: `Use the API Audit Checklist during an API Design Review or another checkpoint before publishing an API to internal or external consumers. Its three phases support APIs at different stages. A broader API capability audit can assess the governance and health of the whole API program; examine the Operating Model Line and the other lines one focus area at a time. Run capability audits quarterly for large programs and annually for smaller teams. Make the audit a collaborative review, not merely a compliance exercise, and turn findings into backlog improvements.` },
  { question: "How do I adapt the method for regulated industries such as finance or healthcare?", answer: `Add regulatory checkpoints to the relevant stations—for example, use the Business Impact, Location, and Capacity canvases at the API Platform Architecture station. Include compliance stakeholders early. Export completed canvases from Canvas Creator as JSON or SVG and keep them in version control to preserve an auditable record of decisions.` },
  { question: "Which roles should be involved at each station when scaling API delivery?", answer: `API Product Strategy typically involves product managers, UX specialists, partner managers, architects, and lead developers. API Design brings together product managers, architects, and lead developers. API Platform Architecture benefits from product management, architecture, platform engineering, security, and governance leads. Metrics & Analytics should include data or analytics teams, platform engineers, product managers, and API support.` },
  { question: "Can APIOps Cycles be used for internal, partner, and public APIs?", answer: `Yes. The same stations, lines, resources, and criteria apply to all three. The context changes inside the work: for example, identify the relevant customer in the Customer Journey Canvas and the API consumers in the API Business Model Canvas. Even for an internal API, the customer journey often starts with the organization’s external customer—and many internal APIs eventually gain a wider audience.` },
  { question: "How do I measure API program maturity using APIOps Cycles?", answer: `Track how regularly teams visit the relevant stations, quality metrics from Metrics & Analytics, governance adoption shown by individual API Audits or capability audits, and consumer adoption indicators such as usage growth and onboarding time.` },
  { question: "How do I get executive buy-in for using the method across the organization?", answer: `For business leaders, use Customer Journey and API Business Model canvases and connect them to business KPIs and adoption data from Monitoring & Improving. For technology leaders, use the Business Impact Canvas and aggregate API Audit results to demonstrate strategic alignment. Share metro-map views of progress and maturity over time, and emphasize reduced delivery risk and faster time to market.` },
  { question: "Can I skip certain stations permanently?", answer: `You can skip a station for now, but not forever. Permanently ignoring API Product Strategy, API Audit, or Monitoring & Improving can create governance gaps and technical debt. API Audit is often one of the best places to start, alongside API Product Strategy when major business or technical changes—or many new and improved APIs—are planned.` },
  { question: "How does APIOps Cycles help us create or improve our API governance model?", answer: `APIOps Cycles turns high-level governance policies into concrete artifacts, recurring practices, and automated checks within API delivery. Link directly to relevant method content, adapt canvases and checklists to your standards, and add internal requirements in your own documentation. You can use the method as-is, customize it, or contribute improvements back to the community. The result combines internal policy with community-tested practices that teams can follow in day-to-day work.` },
];

const pageCopy: Record<Locale, { kicker: string; title: string; description: string; prompt: string }> = {
  en: { kicker: "Help center", title: "Frequently asked questions", description: "Practical answers for teams scaling API delivery, strengthening governance, and adapting APIOps Cycles to complex environments.", prompt: "Select a question to reveal the answer." },
  fi: { kicker: "Ohjekeskus", title: "Usein kysytyt kysymykset", description: "Käytännön vastauksia tiimeille, jotka skaalaavat API-toimituksia, vahvistavat hallintamallia ja soveltavat APIOps Cycles -menetelmää monimutkaisiin ympäristöihin.", prompt: "Avaa vastaus valitsemalla kysymys." },
  fr: { kicker: "Centre d’aide", title: "Questions fréquentes", description: "Des réponses pratiques pour les équipes qui développent la livraison d’API, renforcent leur gouvernance et adaptent APIOps Cycles aux environnements complexes.", prompt: "Sélectionnez une question pour afficher la réponse." },
  de: { kicker: "Hilfe", title: "Häufig gestellte Fragen", description: "Praktische Antworten für Teams, die ihre API-Bereitstellung skalieren, Governance stärken und APIOps Cycles an komplexe Umgebungen anpassen.", prompt: "Wählen Sie eine Frage aus, um die Antwort einzublenden." },
  pt: { kicker: "Central de ajuda", title: "Perguntas frequentes", description: "Respostas práticas para equipas que escalam a entrega de APIs, reforçam a governação e adaptam o APIOps Cycles a ambientes complexos.", prompt: "Selecione uma pergunta para ver a resposta." },
};

export function getFaq(locale: Locale) {
  return { ...pageCopy[locale], items: english };
}
